### ISSUE TITLE
CPUPower

### ISSUE THREAD

**Issue by EndlessDEVOps** [Kudaraidee/yiimp#11]
is the implementation of CPUPOWER working wont accept shares. https://gyazo.com/d2ecd6613a59174141cbb87712fa0948

**Comment by xiaolin1579** [comment]
@CS-JH You can reduce diff in cpupower.conf. https://github.com/Kudaraidee/yiimp/blob/1ceacb101d138ed1e2971d1c8768092d9d6ee0f6/stratum/config.sample/cpupower.conf#L14

**Comment by EndlessDEVOps** [comment]
> @CS-JH You can reduce diff in cpupower.conf.
> 
> https://github.com/Kudaraidee/yiimp/blob/1ceacb101d138ed1e2971d1c8768092d9d6ee0f6/stratum/config.sample/cpupower.conf#L14

what is the recommended diff? tried all the way down to 0.001

**Comment by xiaolin1579** [comment]
> > @CS-JH You can reduce diff in cpupower.conf.
> > https://github.com/Kudaraidee/yiimp/blob/1ceacb101d138ed1e2971d1c8768092d9d6ee0f6/stratum/config.sample/cpupower.conf#L14
> 
> what is the recommended diff? tried all the way down to 0.001

I used 0.2

**Comment by EndlessDEVOps** [comment]
what mining program do you use?

**Comment by xiaolin1579** [comment]
> what mining program do you use?

cpuminer-opt-rplant & SRBMiner-MULTI

**Comment by EndlessDEVOps** [comment]
hmm. tested SRBMiner first and i am on rplant now still gets stuck on stratum connection established
https://gyazo.com/c8e07991d128b728e5e96e3ec0a77bff

**Comment by EndlessDEVOps** [comment]
gonna try to recompile not sure what i am missing here

**Comment by EndlessDEVOps** [comment]
still the same. miner connects but no work being submitted https://gyazo.com/fa08f936cba89a4830a84ce8c05ea011

**Comment by EndlessDEVOps** [comment]
@xiaolin1579 got it hashing(was a dumbass and checked AUX by accident) but blocks are rejecting. is that normal. my settings in backend are as follows (submit block, Txmessage, segwit) and have RPC set as POW

**Comment by xiaolin1579** [comment]
> @xiaolin1579 got it hashing(was a dumbass and checked AUX by accident) but blocks are rejecting. is that normal. my settings in backend are as follows (submit block, Txmessage, segwit) and have RPC set as POW

Yes that's right
