### ISSUE TITLE
compile error stratum

### ISSUE THREAD

**Issue by EndlessDEVOps** [Kudaraidee/yiimp#16]
`ar2/argon2.c:174:5: error: conflicting types for ‘argon2d_hash_encoded’
 int argon2d_hash_encoded(const uint32_t t_cost, const uint32_t m_cost,
     ^
In file included from ar2/argon2.c:22:0:
ar2/argon2.h:267:19: note: previous declaration of ‘argon2d_hash_encoded’ was here
 ARGON2_PUBLIC int argon2d_hash_encoded(const uint32_t t_cost,
                   ^
ar2/argon2.c:185:5: error: conflicting types for ‘argon2d_hash_raw’
 int argon2d_hash_raw(const uint32_t t_cost, const uint32_t m_cost,
     ^
In file included from ar2/argon2.c:22:0:
ar2/argon2.h:260:19: note: previous declaration of ‘argon2d_hash_raw’ was here
 ARGON2_PUBLIC int argon2d_hash_raw(const uint32_t t_cost, const uint32_t m_cost,
                   ^
makefile:46: recipe for target 'ar2/argon2.o' failed
make[1]: *** [ar2/argon2.o] Error 1
make[1]: Leaving directory '/var/yiimp/stratum/algos'
Makefile:41: recipe for target 'projectcode1' failed
make: *** [projectcode1] Error 2`

**Comment by xiaolin1579** [comment]
test form https://github.com/Kudaraidee/yiimp/commit/f1691cfb56f67c8b8900edd0ddeab475079ae1f8

**Comment by jgalode** [comment]
`gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c yespower/crypto/blake2b-yp.c -o yespower/crypto/blake2b-yp.o
gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c a5a.c -o a5a.o
gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c a5amath.c -o a5amath.o
gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c m7m.c -o m7m.o
gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c velvet.c -o velvet.o
gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c argon2a.c -o argon2a.o
gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c blake2/blake2b.c -o blake2/blake2b.o
gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c blake2-ref/blake2b.c -o blake2-ref/blake2b.o
gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c blake2-ref/blake2s.c -o blake2-ref/blake2s.o
gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c ar2/argon2.c -o ar2/argon2.o
ar2/argon2.c:379:1: error: stray ‘\302’ in program
 ▒▒ 2021 GitHub, Inc.
 ^
ar2/argon2.c:379:2: error: stray ‘\251’ in program
 ▒▒ 2021 GitHub, Inc.
  ^
ar2/argon2.c:379:4: error: expected identifier or ‘(’ before numeric constant
 © 2021 GitHub, Inc.
    ^~~~
makefile:46: recipe for target 'ar2/argon2.o' failed
make: *** [ar2/argon2.o] Error 1`

**Comment by EndlessDEVOps** [comment]
quick question on settings for ghostrider RMT have the 5% founders fee set in yiimp still getting rejected blocks any insight into why that might be?

**Comment by xiaolin1579** [comment]
> `gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c yespower/crypto/blake2b-yp.c -o yespower/crypto/blake2b-yp.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c a5a.c -o a5a.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c a5amath.c -o a5amath.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c m7m.c -o m7m.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c velvet.c -o velvet.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c argon2a.c -o argon2a.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c blake2/blake2b.c -o blake2/blake2b.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c blake2-ref/blake2b.c -o blake2-ref/blake2b.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c blake2-ref/blake2s.c -o blake2-ref/blake2s.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c ar2/argon2.c -o ar2/argon2.o ar2/argon2.c:379:1: error: stray ‘\302’ in program ▒▒ 2021 GitHub, Inc. ^ ar2/argon2.c:379:2: error: stray ‘\251’ in program ▒▒ 2021 GitHub, Inc. ^ ar2/argon2.c:379:4: error: expected identifier or ‘(’ before numeric constant © 2021 GitHub, Inc. ^~~~ makefile:46: recipe for target 'ar2/argon2.o' failed make: *** [ar2/argon2.o] Error 1`

fix now

**Comment by xiaolin1579** [comment]
> quick question on settings for ghostrider RMT have the 5% founders fee set in yiimp still getting rejected blocks any insight into why that might be?

You may need to add a code to coinbase.cpp.

**Comment by jgalode** [comment]
> > `gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c yespower/crypto/blake2b-yp.c -o yespower/crypto/blake2b-yp.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c a5a.c -o a5a.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c a5amath.c -o a5amath.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c m7m.c -o m7m.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c velvet.c -o velvet.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c argon2a.c -o argon2a.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c blake2/blake2b.c -o blake2/blake2b.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c blake2-ref/blake2b.c -o blake2-ref/blake2b.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c blake2-ref/blake2s.c -o blake2-ref/blake2s.o gcc -g -ggdb -O2 -I.. -march=native -std=gnu99 -c ar2/argon2.c -o ar2/argon2.o ar2/argon2.c:379:1: error: stray ‘\302’ in program ▒▒ 2021 GitHub, Inc. ^ ar2/argon2.c:379:2: error: stray ‘\251’ in program ▒▒ 2021 GitHub, Inc. ^ ar2/argon2.c:379:4: error: expected identifier or ‘(’ before numeric constant © 2021 GitHub, Inc. ^~~~ makefile:46: recipe for target 'ar2/argon2.o' failed make: *** [ar2/argon2.o] Error 1`
> 
> fix now

compilation works but when I run the pool there is no reaction BCRS the cryptocurrency does not work (argon2d16000)

**Comment by EndlessDEVOps** [comment]
> > quick question on settings for ghostrider RMT have the 5% founders fee set in yiimp still getting rejected blocks any insight into why that might be?
> 
> You may need to add a code to coinbase.cpp.

yea that is a bit beyond me thank you for the reply
