### ISSUE TITLE
coin_form.php

### ISSUE THREAD

**Issue by champmine** [Kudaraidee/yiimp#18]
after installation on  fresh ubuntu 18, the coin_form.php is fault, the submit button is not shown
can you fix this please?
and why do you close issues that are not fixed yet?

**Comment by xiaolin1579** [comment]
set port?

**Comment by champmine** [comment]
yes, set port faulty, but other fields too, I think it has something to do with the install script, possibly not all needed fields are in the database? I tried both eskal and xavatar install scripts

Do you have documentation for a step by step installation without install script?

**Comment by Delari** [comment]
u fix this?

**Comment by MonkeyD-Core** [comment]
You can fix that with this https://github.com/Kudaraidee/yiimp/pull/41

**Comment by afiniel** [comment]
What installer are you use? i see you use an installer that is outdated php atleast. prob an installer with php7.2
