### ISSUE TITLE
new yespower coin based on dash PRIV

### ISSUE THREAD

**Issue by champmine** [Kudaraidee/yiimp#22]
do you think you can include PRIVCY coin, yespower based on a dash fork
min difficulty is 0x00ffffffff.... in double about 3e-8
if you can it would be fantastic, if you cannot please give me a hint how to do this
source PRIV is here
https://github.com/Bob-bit-PRIV/PRiVCY

**Comment by nitrocon** [comment]
yespower algo is implemented, you have to add the coin youreself, pls close this issue
