### ISSUE TITLE
multipool_single db.sh

### ISSUE THREAD

**Issue by champmine** [Kudaraidee/yiimp#25]
db.sh broken referring to a database no longer available in your tree

sudo zcat 2019-11-10-yiimp.sql.gz | sudo mysql -u root -p"${DBRootPassword}" "${YiiMPDBName}"

2021-06-21-yaamp.sql.gz 
gzip: 2021-06-21-yaamp.sql.gz: not in gzip format

**Comment by xiaolin1579** [comment]
use unrar
