### ISSUE TITLE
add support for sha3

### ISSUE THREAD

**Issue by JayBitron** [Kudaraidee/yiimp#32]
Hello, I was wondering if it's possible to add support for sha3 algorithm:

https://bitcointalk.org/index.php?topic=5125675.0

Thanks!

**Comment by xiaolin1579** [comment]
https://github.com/Kudaraidee/yiimp/tree/sha3d

**Comment by JayBitron** [comment]
it doesn't work with witness enabled coins like Yilacoin, mining works, it accepts shares, but when a block is mined, the client rejects the block.

**Comment by crackfoo** [comment]
that's not the algo's fault. if the coin has segwit, then enable segwit
along with coding any other non-standard block requirements.
