### ISSUE TITLE
yiimp white blank page

### ISSUE THREAD

**Issue by Delari** [Kudaraidee/yiimp#39]
i have white blank page on /site/AdminPortal page

http://192.168.0.26/ pool main page open

from similar topics, I realized that I need to install an additional package

`sudo apt-get install -y php7.3-memcache`

add enable to systemctl and restart service but this not help
logs: `/var/log/nginx/192.168.3.26.app-access.log`
`192.168.0.90 - - [26/Apr/2022:17:41:05 +0000] "GET /site/AdminPortal HTTP/1.1" 200 34 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWe`

any ideas?

**Comment by Delari** [comment]
Access to the admin panel was carried out along the path /site/myadmin - not /site/AdminPanel

**Comment by diabaths** [comment]
if i want to change the myadmin  path where is located?

**Comment by xiaolin1579** [comment]
> if i want to change the myadmin path where is located?

https://github.com/Kudaraidee/yiimp/blob/dev/web/yaamp/modules/site/SiteController.php#L11
