### ISSUE TITLE
No submitted hash displayed in DGB and PPC screen -r on U 16.4 and 18

### ISSUE THREAD

**Issue by lurchinms** [Kudaraidee/yiimp#4]
22:12:39: PPC 501090 - diff 2875083572.455158234 job 2 to 2/2/2 clients, hash 14268291.424/0.000 in 0.1 ms
[1] Txes count: 0
[1] Txes count: 0
[1] Txes count: 0
22:13:42: PPC 501090 - diff 2875083572.455158234 job 3 to 2/2/2 clients, hash 21372771.289/0.000 in 0.1 ms
[1] Txes count: 0
[1] Txes count: 0
[1] Txes count: 0
22:14:45: PPC 501090 - diff 2875083572.455158234 job 4 to 2/2/2 clients, hash 24889184.020/0.000 in 0.1 ms
22:14:48: coind->height differs from rpc response, forcing new template (501089 vs 501090)..
[1] Txes count: 0
22:14:48: PPC 501091 - diff 2880644776.364585400 job 5 to 2/2/2 clients, hash 24889184.020/0.000 in 0.0 ms
[1] Txes count: 0
[1] Txes count: 0
[1] Txes count: 0
[1] Txes count: 0
22:15:49: PPC 501091 - diff 2880644776.364585400 job 6 to 2/2/2 clients, hash 26948049.290/0.000 in 0.1 ms

**Comment by xiaolin1579** [comment]
I'm not sure what caused it

**Comment by lurchinms** [comment]
Why does it show Txes counts all the time?

**Comment by xiaolin1579** [comment]
> Why does it show Txes counts all the time?
I was trying to add YespowerRES, an algorithm that combines Equihash and yespower, but I failed, so I didn't continue.

**Comment by xiaolin1579** [comment]
> Why does it show Txes counts all the time?

Check the number of transactions at that time.

But if you want to turn off the "Txes count" messages you need to change these files and recompile stratum.
stratum/client_sumbit.cpp
stratum/coind_template.cpp

In those files there is a line starting with std::cerr followed by the Txes count message. Just put a // in front of this line.

**Comment by lurchinms** [comment]
Cool thanks. I though I may have been missing something in my conf files. I will try that at on the next stratum builds.

**Comment by lurchinms** [comment]
> > Why does it show Txes counts all the time?
> 
> Check the number of transactions at that time.
> 
> But if you want to turn off the "Txes count" messages you need to change these files and recompile stratum.
> stratum/client_sumbit.cpp
> stratum/coind_template.cpp
> 
> In those files there is a line starting with std::cerr followed by the Txes count message. Just put a // in front of this line.

Did you remove them? I just download it again to test on EMC2 and do not see the TX messages.
