### ISSUE TITLE
solo function trouble

### ISSUE THREAD

**Issue by bangdrie** [Kudaraidee/yiimp#42]
Can someone help please? There is a miner in my pool with 10 workers. 4 of them are mining solo. If ANY of his rigs find a block, he gets paid the whole block reward just like all his workers are in solo. Also, if any other miner hits a block, he gets a share according to his hashrates! How to fix that?

**Comment by c5yal8r** [comment]
Is the miner using the same address for all 10 workers?

**Comment by bangdrie** [comment]
yes, using same address

**Comment by bangdrie** [comment]
> Is the miner using the same address for all 10 workers?

yes, using same address

**Comment by AzrelixJ** [comment]
Having the same issue

If someone uses the same wallet address for both SOLO and SHARED mining, all blocks found by that wallet address are counted as SOLO, but still getting his portion of the SHARED blocks found by any other miner on the shared pool.

**Comment by bangdrie** [comment]
this issue was fixed!! thanks
