### ISSUE TITLE
ocv2 algo

### ISSUE THREAD

**Issue by papagruz** [Kudaraidee/yiimp#49]
Hello. Way remove ocv2 algo? 
Algo be added agein?
Thanks.

**Comment by xiaolin1579** [comment]
The build process is quite complicated.

**Comment by xiaolin1579** [comment]
looking for way

**Comment by xiaolin1579** [comment]
[Stratum: Add Ocv2 Algorithm [Ocvcoin]](https://github.com/Kudaraidee/yiimp/commit/4f5da34633c6b6f982314ea5f7c4c026e4d04872)
