### ISSUE TITLE
can`t compile stratum after add ocv2 algo

### ISSUE THREAD

**Issue by papagruz** [Kudaraidee/yiimp#50]
Thenks you for add ocv2 algo, but after add cant compile stratum, have errorr when make -C algos:
No package 'opencv' found
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
ocv2.cpp:3:10: fatal error: opencv2/opencv.hpp: No such file or directory
 #include <opencv2/opencv.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
makefile:43: recipe for target 'ocv2.o' failed
make: *** [ocv2.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/home/papagruz/yiimp/stratum/algos'

**Comment by xiaolin1579** [comment]
Hmm, maybe there's a problem compiling ocv2_algo.

**Comment by xiaolin1579** [comment]
what version of ubuntu are you using?

**Comment by xiaolin1579** [comment]
https://github.com/furcalor/ocv2_algo/tree/master/How-Do-We-Add-OCV2-To-The-Stratum#readme

**Comment by papagruz** [comment]
Thanks, try add

**Comment by papagruz** [comment]
Recompile ocv2_algo from source and error fix. Thank you

**Comment by xiaolin1579** [comment]
I moved the ocv2 to a new branch and deleted it from the dev.
https://github.com/Kudaraidee/yiimp/tree/ocv2
