### ISSUE TITLE
Curvehash rejecting blocks!

### ISSUE THREAD

**Issue by GetRekt69420** [Kudaraidee/yiimp#54]
![image](https://user-images.githubusercontent.com/83239093/190853755-ffc727e3-6ae1-4bb9-aa1a-be634332b315.png)

**Comment by xiaolin1579** [comment]
set rpc type is pos

**Comment by GetRekt69420** [comment]
> set rpc type is pos

will give it a try and report back when block hits!
thanks!

**Comment by GetRekt69420** [comment]
> set rpc type is pos

**Issue Solved!!!!!**
