### ISSUE TITLE
sql/2021-06-21-yaamp.sql.gz appears to be a RAR file

### ISSUE THREAD

**Issue by itsgudenuf** [Kudaraidee/yiimp#55]
zcat 2021-06-21-yaamp.sql.gz  fails
unrar e 2021-06-21-yaamp.sql.gz produces 2021-06-21-yaamp.sql 

What's the best way to get this file replaced in the repo as a gzip file

**Comment by xiaolin1579** [comment]
https://github.com/Kudaraidee/yiimp/issues/28

**Comment by xiaolin1579** [comment]
the file have use rar compressor unrar and them you can use
