### ISSUE TITLE
solo doesn't work

### ISSUE THREAD

**Issue by seoseo29** [Kudaraidee/yiimp#58]
Hello, I installed the pool, everything beckons, I set the password for SOLO c = FEAT,m= solo, but solo does not charge, but charges prop, something needs to be configured separately?

**Comment by xiaolin1579** [comment]
YAAMP_FEES_SOLO in /var/web/serverconfig.php

**Comment by seoseo29** [comment]
there is a parameter of 1, solo does not work, what should I put? define('YAAMP_FEES_SOLO', 1);

**Comment by xiaolin1579** [comment]
are you sure you use this Kudaraidee-yiimp

**Comment by xiaolin1579** [comment]
/var/web/yaamp/core/backend/blocks.php
https://github.com/Kudaraidee/yiimp/blob/dev/web/yaamp/core/backend/blocks.php#L96

**Comment by itsgudenuf** [comment]
I set this in my /var/web/serverconfig.php
define('YAAMP_FEES_SOLO', 0.0);

It seems to work fine.  It was 0.5 which  worked.

When I change these settings, I already restart memcached and php7.3-fpm

**Comment by xiaolin1579** [comment]
> I set this in my /var/web/serverconfig.php define('YAAMP_FEES_SOLO', 0.0);
> 
> It seems to work fine. It was 0.5 which worked.
> 
> When I change these settings, I already restart memcached and php7.3-fpm

yes, solo fee 0.5%

**Comment by seoseo29** [comment]
solo should be 99% [url=https://ibb.co/M6B0WpY][img]https://i.ibb.co/xHFTPGp/2022-09-25-14-31-10.jpg[/img][/url]
[url=https://ru.imgbb.com/]jpg bmp gif[/url]

**Comment by xiaolin1579** [comment]
> solo should be 99% [url=https://ibb.co/M6B0WpY][img][https://i.ibb.co/xHFTPGp/2022-09-25-14-31-10.jpg[/img][/url]](https://i.ibb.co/xHFTPGp/2022-09-25-14-31-10.jpg%5B/img%5D%5B/url%5D) [url=https://ru.imgbb.com/]jpg bmp gif[/url]

make sure he actually found block

**Comment by seoseo29** [comment]
I've tried everything, solo doesn't work

**Comment by xiaolin1579** [comment]
Did you put m=solo on all machines?

**Comment by seoseo29** [comment]
yes, c=FITA,m=solo

**Comment by xiaolin1579** [comment]
There seems to be some bug in clearing worker solo from block share.

**Comment by xiaolin1579** [comment]
This allows solo users to still receive shares from shared users, but shared users will not receive shares from solo users.

**Comment by seoseo29** [comment]
can I fix it?

**Comment by xiaolin1579** [comment]
https://github.com/Kudaraidee/yiimp/commit/e9c5e2fee81672cf646cc9a852c8687bee353d47

**Comment by xiaolin1579** [comment]
https://github.com/Kudaraidee/yiimp/commit/1173628e7c1de71d6a2b980f5dc29938984a54d6
