### ISSUE TITLE
stratum solve block fail, reason: high-hash

### ISSUE THREAD

**Issue by wong-fi-hung** [Kudaraidee/yiimp#59]
Algorithm: yespower
currency: onyx
coind: onyxd

this is log from debug.log file:
2022-10-17T15:29:09Z ERROR: ProcessNewBlock: AcceptBlock FAILED (high-hash, proof of work failed (code 16))

**Comment by xiaolin1579** [comment]
Maybe the stratum diff is set too low.
This error is common for CPU-intensive algorithms.

**Comment by wong-fi-hung** [comment]
> Maybe the stratum diff is set too low. This error is common for CPU-intensive algorithms.

hmm, okay.
mybe the stratum diff settings is too low is true.
I used for testing on difficulty 0.01.
and i will try to increasing the stratum diff to 0.1 and i will see what happend.
