### ISSUE TITLE
Hashrate

### ISSUE THREAD

**Issue by says112** [Kudaraidee/yiimp#65]
The hashrate of the sha 256 algorithm is not reflected on the pool, although the balls are located and the miners are working properly.
![Снимок экрана (256)](https://user-images.githubusercontent.com/22127398/197727374-6c878ad7-125d-4e80-89aa-86f3c61c07cd.png)
![Снимок экрана (257)](https://user-images.githubusercontent.com/22127398/197727422-6893b4e7-37bf-4ce9-ada2-712414fed909.png)

**Comment by xiaolin1579** [comment]
not sure. try see Workers 
![image](https://user-images.githubusercontent.com/10980342/197744851-aa945397-8b93-4aa8-8fb9-14d5671fd4de.png)

**Comment by says112** [comment]
The workers are empty.
![Uploading Снимок экрана (258).png…]()

**Comment by says112** [comment]
![Снимок экрана (258)](https://user-images.githubusercontent.com/22127398/197755702-fe29dbaa-d40f-45e7-81b1-9da8a8bfec9a.png)

**Comment by xiaolin1579** [comment]
Select Algo = sha256
![image](https://user-images.githubusercontent.com/10980342/197772370-57291200-cdc7-4e55-b727-d8c39419fbce.png)

**Comment by luckyshibe** [comment]
Having the same issue, is there a fix for this?

**Comment by xiaolin1579** [comment]
used sha256d algo

**Comment by afiniel** [comment]
Yes Its fixed on this https://github.com/Kudaraidee/yiimp/pull/99#event-9534335494
