### ISSUE TITLE
1 algo with multi coin using multi port.

### ISSUE THREAD

**Issue by wong-fi-hung** [Kudaraidee/yiimp#66]
how to configure based one algo, but have more than one coin with multiple port's.

example:  yespower algo and the coind is onyx and bitweb.
is possible to use different port on some algos..?
please help...

**Comment by papagruz** [comment]
Make stratum.conf for for each port and add to conf:
 [WALLETS]
    include = coin symbol

**Comment by wong-fi-hung** [comment]
the mean coin symbol, is like BTC or what ever the coint want to make different with other..?

**Comment by papagruz** [comment]
![image](https://user-images.githubusercontent.com/35342330/197944345-3c818845-75e7-45ef-a9cc-b3707a5498d3.png)
![image](https://user-images.githubusercontent.com/35342330/197944573-d8bd66eb-ced7-4fd2-a23a-1cb8c73963c2.png)
![image](https://user-images.githubusercontent.com/35342330/197944466-5eb09c01-4c40-45e0-ae03-9c2d30b60ac2.png)

**Comment by wong-fi-hung** [comment]
included in 1 config or using 2 config...?

**Comment by papagruz** [comment]
In all config
and start stratum
![image](https://user-images.githubusercontent.com/35342330/197995404-afcf126f-ffad-4cc1-ab8d-d72c6726b263.png)

**Comment by wong-fi-hung** [comment]
okay, thankyou..
the problems now have resolved.
and this issue is closed from now.

regards:
wong-fi-hung
