### ISSUE TITLE
error 10

### ISSUE THREAD

**Issue by diabaths** [Kudaraidee/yiimp#67]
i have install the first coin and i get this error
https://gyazo.com/6584bbccae9a00ff5ebeb1af88a1edbe

https://gyazo.com/6c4128922ac2c02177bfa1ab1844afea

**Comment by nitrocon** [comment]
well, pls join the discord you will have more questions

that error field is more or less an informationfield, its all okay with youre atanapi, its downloading blocks and syncing he blockchain, until that, the stratums cant connect to the blocktemp...so, first syncing, then mining.

**Comment by xiaolin1579** [comment]
https://discord.gg/DRspMUjYxV
