### ISSUE TITLE
pool status 

### ISSUE THREAD

**Issue by diabaths** [Kudaraidee/yiimp#68]
while i adding coins in my pool, i cant see them in pool status every time i add a coin i can see only the last installed coin

https://gyazo.com/6c362b0ec237b9ad2770aeb86b79dc83

https://gyazo.com/28ab2f83a6499f916ddf1533656db4f1

**Comment by diabaths** [comment]
fixed i was missing this 
ALTER TABLE `shares` ADD `solo` TINYINT(1) NULL DEFAULT NULL AFTER `algo`;

**Comment by xiaolin1579** [comment]
ok
