### ISSUE TITLE
Found Solo Blocks not shown in users wallet and get not payed by system

### ISSUE THREAD

**Issue by nitrocon** [Kudaraidee/yiimp#69]
Hi,
unrelated to the coin where that issue is, I have tested this with 3 different coins, all solo found blocks are not displayed in the wallet of the miner and get not payed out by the system, all rewards are payed to the pool address.

**Comment by xiaolin1579** [comment]
strange

**Comment by nitrocon** [comment]
solved, after updating php I had to reboot so dbus-daemon could update as well...
