### ISSUE TITLE
dont show the blocks (solve)

### ISSUE THREAD

**Issue by diabaths** [Kudaraidee/yiimp#70]
https://gyazo.com/269ce4c8f9b37deeeb693df63cfa81fc

if i go into the coin i can see it normaly
https://gyazo.com/8cd3422d29bab7dad36b5ff751b3f00a

solved

**Comment by nitrocon** [comment]
blocks in the admin sections will only show if they have been found...
and youre wallet should be fully synced
btw for FITA, dont use port 80....thats a system port
