### ISSUE TITLE
Stratum issues after last update

### ISSUE THREAD

**Issue by papagruz** [Kudaraidee/yiimp#88]
Hello. I try add last update to my pool. Bat have problem with stratum. In stratum add mine_port, i add column mine_port in my db, but stratum giver error: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'.
How fix this error?

**Comment by xiaolin1579** [comment]
coins -> mine_port

**Comment by xiaolin1579** [comment]
`ALTER TABLE coins ADD mine_port INT NULL AFTER specifications;`

**Comment by papagruz** [comment]
Thanks it`s help. I added tables in stratum and not add to coins. Now all work!

**Comment by MonkeyD-Core** [comment]
ERROR Port number ended with 'P'

**Comment by Beanservers** [comment]
> Thanks it`s help. I added tables in stratum and not add to coins. Now all work!

how do you do this please ive been trying for days :(  thank you
